import Foundation

/// Where an explanation's text actually came from. The UI uses this to label
/// output honestly: AI-generated prose looks different from rule-based template
/// stitching, and both look different from a raw YAML fallback.
public enum ExplanationSource: Sendable, Equatable {
    /// Generated by the local MLX model.
    case ai
    /// Built from `TemplateInferenceEngine` — structured, rule-driven, no model.
    case template
    /// Pulled straight from the YAML rule's `explanation` field; the engine
    /// was unavailable, failed to load, or threw mid-call.
    case rule
}

/// An explanation of a scan result, with metadata about how it was generated.
public struct AIExplanation: Sendable, Equatable {
    /// The explanation text.
    public let text: String

    /// Whether this came from AI inference or YAML rule fallback.
    public let source: ExplanationSource

    public init(text: String, source: ExplanationSource) {
        self.text = text
        self.source = source
    }
}

/// Current lifecycle state of the AI model.
public enum AIModelLifecycleState: Sendable, Equatable {
    /// No model loaded in memory.
    case unloaded
    /// Model is being loaded into memory.
    case loading
    /// Model is loaded and ready for inference.
    case ready
}

/// Protocol for on-device AI services (Tier 1: local MLX inference).
///
/// Conforming types manage model lifecycle (lazy load, eager unload)
/// and provide explanation generation for scan results.
/// AI explanations are advisory only — they never change safety classifications.
@MainActor
public protocol AIServiceProtocol: AnyObject, Sendable {
    /// Current lifecycle state of the model.
    var lifecycleState: AIModelLifecycleState { get }

    /// Whether a downloaded model file exists on disk.
    var isModelAvailable: Bool { get }

    /// Approximate memory used by the loaded model, in bytes.
    var modelMemoryUsage: Int64 { get }

    /// Generate an explanation for a scan result.
    ///
    /// If the model is not loaded, it will be loaded lazily on first call.
    /// If no model is available on disk, falls back to the YAML rule explanation.
    /// Each call resets the idle unload timer.
    ///
    /// - Parameters:
    ///   - result: The scan result to explain.
    ///   - rule: The YAML rule that matched this result.
    /// - Returns: An explanation with source metadata.
    func explain(result: ScanResult, rule: ScanRule) async throws -> AIExplanation

    /// Produce a short post-cleanup narrative (1–2 sentences) for display in
    /// `CleanupSummaryView`.
    ///
    /// Non-throwing: always returns a usable `CleanupNarrative`. When no model
    /// is available on disk, the engine fails to load, or the engine throws
    /// during generation, falls back to a deterministic template narrative
    /// derived from the `CleanupResult`'s own fields. Display-only — the
    /// narrative is not persisted to the audit record.
    func narrate(cleanup result: CleanupResult) async -> CleanupNarrative

    /// Explicitly unload the model from memory.
    func unloadModel()
}
