import Foundation

public enum CommandActionRuleCategory {
    public static let developer = "developer_tool_command"
    public static let advanced = "advanced_command_action"
}

/// A declarative, YAML-driven cleanup rule that runs an external tool command
/// rather than deleting filesystem paths directly.
///
/// Where `ScanRule` describes "look for these paths and classify them",
/// `CommandActionRule` describes "ask this tool to clean itself, with these
/// exact arguments, and capture the outcome." The Trust Layer treats both
/// shapes uniformly: explainable, bounded, reversible (or escalated to
/// `review`), and audited.
///
/// Examples in the bundled starter set:
/// - `xcrun simctl delete unavailable` — removes orphaned simulator runtimes
/// - `pnpm store prune` — removes unreferenced package store entries
/// - `go clean -cache` — removes the Go build cache
public struct CommandActionRule: Codable, Sendable, Identifiable, Equatable {
    /// Stable unique identifier (e.g., "simctl_delete_unavailable").
    public let id: String

    /// Human-readable name (e.g., "Xcode Simulator (orphaned runtimes)").
    public let name: String

    /// The tool key used to resolve the executable on disk
    /// (e.g., "xcrun", "pnpm", "go", "brew", "docker"). The
    /// `CommandActionToolResolver` maps this to a candidate path list.
    public let tool: String

    /// Full argument list passed after the resolved binary. No shell
    /// interpolation is performed; arguments are passed verbatim to
    /// `posix_spawn`.
    public let arguments: [String]

    /// Optional argument list that produces a dry-run preview. When present,
    /// the executor uses it to estimate `bytes_reclaimable` before the
    /// destructive run. When absent, the effective safety classification
    /// downgrades to `.review` regardless of the YAML's declared `safety`,
    /// per the Trust Layer requirement: "no dry-run means review, not safe."
    public let dryRunArguments: [String]?

    /// Trust Layer safety classification declared in YAML. May be downgraded
    /// to `.review` at preview time when no dry-run estimate is available.
    public let safety: SafetyLevel

    /// Confidence percentage (0–100) in the safety classification.
    public let confidence: Int

    /// One-line explanation of what running this command does and why it's
    /// classified the way it is. Surfaced in the cleanup confirmation flow.
    public let explanation: String

    /// Explicit consequence copy for review/advanced command actions. This is
    /// appended to the surfaced explanation so confirmation dialogs describe
    /// the likely restore cost before the user runs the tool-native cleanup.
    public let consequence: String?

    /// Scan category for grouping and profile filtering.
    /// Convention: `developer_tool_command` for developer tooling commands.
    public let category: String

    /// Whether the affected data is regenerated by routine use of the tool.
    public let regenerates: Bool

    /// Optional user-facing hint for how the data is regenerated.
    public let regenerateCommand: String?

    /// Filesystem roots the command is expected to touch, declared up front.
    /// The cleanup pipeline cross-checks these against the protected-roots
    /// policy before scheduling the command — a rule that claims to touch a
    /// protected root is rejected at registration, not at execution.
    public let affectedRoots: [String]

    /// Bounded set of preconditions the executor checks before running.
    public let preconditions: CommandActionPreconditions

    /// Attribution for the tool or product whose data this command targets.
    public let source: SourceAttribution

    /// Optional tags for filtering and grouping in the UI.
    public let tags: [String]

    public init(
        id: String,
        name: String,
        tool: String,
        arguments: [String],
        dryRunArguments: [String]? = nil,
        safety: SafetyLevel,
        confidence: Int,
        explanation: String,
        consequence: String? = nil,
        category: String,
        regenerates: Bool = false,
        regenerateCommand: String? = nil,
        affectedRoots: [String] = [],
        preconditions: CommandActionPreconditions = CommandActionPreconditions(),
        source: SourceAttribution,
        tags: [String] = []
    ) {
        self.id = id
        self.name = name
        self.tool = tool
        self.arguments = arguments
        self.dryRunArguments = dryRunArguments
        self.safety = safety
        self.confidence = confidence
        self.explanation = explanation
        self.consequence = consequence?.trimmingCharacters(in: .whitespacesAndNewlines)
        self.category = category
        self.regenerates = regenerates
        self.regenerateCommand = regenerateCommand
        self.affectedRoots = affectedRoots
        self.preconditions = preconditions
        self.source = source
        self.tags = tags
    }

    /// Display string assembled from `tool` and `arguments`, e.g.
    /// `"xcrun simctl delete unavailable"`. Used in audit entries and UI.
    public var commandDisplay: String {
        ([tool] + arguments).joined(separator: " ")
    }
}

/// Bounded, declarative preconditions the executor enforces before running
/// a command rule. Kept narrow on purpose — anything that needs imperative
/// logic belongs in the adapter, not the YAML.
public struct CommandActionPreconditions: Codable, Sendable, Equatable {
    /// Maximum wall-clock seconds the command may run before being killed.
    /// Bounded to keep a stuck tool from holding the cleanup pipeline open.
    public let timeoutSeconds: TimeInterval

    public init(timeoutSeconds: TimeInterval = 60) {
        self.timeoutSeconds = timeoutSeconds
    }
}

/// Top-level container for a YAML command-rule file. Parallel to `RuleFile`.
public struct CommandActionRuleFile: Codable, Sendable {
    public let rules: [CommandActionRule]

    public init(rules: [CommandActionRule]) {
        self.rules = rules
    }
}
